apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/flask-app"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-app-pvc
  namespace: flask-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

