apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-page-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-page-app
  template:
    metadata:
      labels:
        app: main-page-app
    spec:
      containers:
      - name: main-page-app
        image: vancleefy/main-page-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: main-page-app-service
spec:
  selector:
    app: main-page-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

