apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flutter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flutter-app
  template:
    metadata:
      labels:
        app: my-flutter-app
    spec:
      containers:
        - name: my-flutter-app
          image: vancleefy/my_flutter_app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-flutter-app-service
spec:
  selector:
    app: my-flutter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
